name: Deploy Node.js App

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Stop Old Application
        run: |
          if [ -f /home/ubuntu/node-demo/app.pid ]; then
            PID=$(cat /home/ubuntu/node-demo/app.pid)

            if kill -0 "$PID" 2>/dev/null; then
              kill "$PID"
              sleep 2
            fi

            rm -f /home/ubuntu/node-demo/app.pid
          fi


      - name: Copy New Application
        run: |
          rm -rf /home/ubuntu/node-demo
          mkdir -p /home/ubuntu/node-demo
          cp -r . /home/ubuntu/node-demo

      - name: Start Application
        run: |
          mkdir -p /home/ubuntu/node-demo
          cd /home/ubuntu/node-demo

          RUNNER_TRACKING_ID="" nohup node server.js > app.log 2>&1 &

          echo $! > app.pid

      - name: Verify Deployment
        run: |
          sleep 5
          curl --fail http://localhost:5000/hello